
server:
  port: 8080
  servlet:
    context-path: /


pagehelper:
  helper-dialect: mysql

mybatis:
  type-handlers-package: com.springmall.handler

spring:
  profiles:
    active: db

mall:
  aliyun:
    oss:
      bucket: cskaoyan
      end-point: oss-cn-beijing.aliyuncs.com
    sms:
      sign-name: 王道训练营
      template-code: SMS_173765187
      region-id: cn-hangzhou

